name: Rust Build

permissions:
  contents: write

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release --verbose

    - name: Compress Artifacts
      uses: vimtor/action-zip@1.1
      with:
        files: target/release/dr_symlogger_launcher.exe cmd.bat
        dest: ${{ github.event.repository.name }}-${{ github.sha }}.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ${{ github.event.repository.name }}-${{ github.sha }}.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.event.repository.name }}-${{ github.sha }}.zip

